server:
  port: 8080
spring:
  datasource:
    password:
    username:
    url: jdbc:postgresql://localhost:5432/mydb
    driver-class-name: org.postgresql.Driver
flyway:
  baseline-on-migrate: true
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop
      default_schema: friend_service
